### PR TITLE
Fixes for IDENTITY-3048

### PR DESCRIPTION
**Pull request by chanukaranaba**

### CODE REVIEW

**Comment by chanukaranaba** [comment]
This contains fixes for disabled property checkbox making optional in User Store Manager, when selecting org.wso2.carbon.identity.user.store.remote.CarbonRemoteUserStoreManager.

**Comment by johannnallathamby** [comment]
Hi I think we can fix the same in all the UserStoreManagers, not only CarbonRemoteUserStoreManager.

**Comment by chanukaranaba** [comment]
Fixes for,
org.wso2.carbon.user.core.ReadWriteLDAPUserStoreManager, org.wso2.carbon.user.core.ReadOnlyLDAPUserStoreManager and  org.wso2.carbon.user.core.ldap.ActiveDirectoryUserStoreManager are in user.core in kernal. I will send another PR for those.

**Comment by chanukaranaba** [comment]
Fixes in the previous comments were fixed in [1]
[1] https://github.com/wso2/carbon4-kernel/pull/138

**Comment by chanukaranaba** [comment]
closing the PR due to conflicts. Will send a separate PR with same fixes.

**Pull request closed without merging**
